import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'
import useSWR from 'swr'

import styles from '../styles/Home.module.css'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Home() {
  const { data, mutate, isValidating } = useSWR('/api/get-entries', fetcher)

  function addNewEntry(event) {
    event.preventDefault()

    const text = event.target.children.text.value

    fetch('/api/hi', {
      method: 'POST',
      body: JSON.stringify({ text }),
      headers: { 'Content-Type': 'application/json' },
    }).then(() => {
      event.target.children.text.value = ''
      mutate('/api/get-entries')
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hi</h1>

        <form onSubmit={addNewEntry}>
          <input type="text" name="text" />

          <button type="submit">Add new entry</button>
        </form>

        {!data || isValidating ? null : (
          <>
            <ul>
              {data?.results?.map(({ properties, id }) => {
                return (
                  <li key={id}>{properties?.Name?.title[0]?.plain_text}</li>
                )
              })}
            </ul>
          </>
        )}
      </main>
    </div>
  )
}
